---
sudo:
  - username: kcoakley
    permissions:
      - command: ALL
        nopasswd: true
  - username: wmarkuske
    permissions:
      - command: ALL
        nopasswd: true
  - username: dbsaba
    permissions:
      - command: ALL
        nopasswd: true
